version: "3.9"
services:
    php:
        image: mobtitude/php-xdebug:8.0-cli
        entrypoint: ["/usr/local/bin/php"]
        command: ["/app/bin/php-collection-generator", "--config", "/app/example/php-collection-generator.json", "generate", "/app/example/output"]
        ports:
            - "9000:9000"
        user: "${DOCKER_USER}"
        volumes:
            - ./:/app
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
